### ISSUE TITLE
Update Project page located at docs/index.html with Readme.md info

### ISSUE THREAD

**Issue by JohanAltamar** [JohanAltamar/orderTrackingApp#77]

**Comment by JohanAltamar** [comment]
If you want to know how to contribute, leave a comment.

**Comment by Spring-dot** [comment]
I want to know and contribute.

**Comment by JohanAltamar** [comment]
> I want to know and contribute.

Hi, nice to see you here. You only will need HTML, CSS and git knowledge to upload the contibrution.

**Comment by Spring-dot** [comment]
@JohanAltamar I have knowledge of HTML, CSS, and git. Since I am a beginner so please guide me in this. Should I read the code and start?

**Comment by JohanAltamar** [comment]
Not the code but readme.md :) Add that info and it would be awesome if you can add the stylesheet :)

**Comment by JohanAltamar** [comment]
so you will have to: 
1. Fork the repository
2. Create a new branch (git checkout -b [branch name])
3. Add your files
4. Push files changed 
5. Create a new pull request and wait for approval :)

**Comment by Spring-dot** [comment]
@JohanAltamar Thanks! I will complete it soon! :)

**Comment by JohanAltamar** [comment]
@Spring-dot what other skills do you have?

**Comment by Spring-dot** [comment]
@JohanAltamar  I know python and its framework Django, Flask. For frontend I have learnt JS and react library, and will complete nodejs soon! :)
